name: Deploy front-page to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - front-page/**
      - frontstage_deploy(production).yaml
  pull_request:
    branches:
      - main
    paths:
      - front-page/**
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use a stable LTS version of Node.js

      - name: Install dependencies
        working-directory: ./front-page
        run: npm install 

      - name: Build
        env:
          VUE_APP_API_BASE: ''  # Replace this with any Vue environment variables you need
        working-directory: ./front-page
        run: npm run build  # Vue.js uses `npm run build` to generate the production files

      - name: Install Wrangler
        run: npm install -g wrangler 

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUD_FLARE_DEPLOY_API_TOKEN }}
          accountId: ${{ secrets.CLOUD_FLARE_DEPLOY_ACCOUNT_ID }}
          command: pages deploy ./front-page/dist --project-name=btc-rise-calling --commit-dirty=true
          quiet: false
